-- Add multidisciplinary expertise areas to support various professional domains
-- This expands the platform beyond IT to include healthcare, counseling, business, and other industries

INSERT INTO public.expertise_areas (id, name, description) VALUES
-- Healthcare & Medical
(gen_random_uuid(), 'General Medicine', 'General medical practice and primary care'),
(gen_random_uuid(), 'Cardiology', 'Heart and cardiovascular system health'),
(gen_random_uuid(), 'Dermatology', 'Skin conditions and treatments'),
(gen_random_uuid(), 'Pediatrics', 'Child and adolescent healthcare'),
(gen_random_uuid(), 'Psychiatry', 'Mental health diagnosis and treatment'),
(gen_random_uuid(), 'Neurology', 'Nervous system disorders and brain health'),
(gen_random_uuid(), 'Orthopedics', 'Bone and joint health'),
(gen_random_uuid(), 'Oncology', 'Cancer diagnosis and treatment'),
(gen_random_uuid(), 'Emergency Medicine', 'Emergency and urgent care'),
(gen_random_uuid(), 'Surgery', 'Surgical procedures and techniques'),
(gen_random_uuid(), 'Radiology', 'Medical imaging and diagnostics'),
(gen_random_uuid(), 'Anesthesiology', 'Anesthesia and pain management'),
(gen_random_uuid(), 'Obstetrics & Gynecology', 'Women''s health and pregnancy care'),
(gen_random_uuid(), 'Urology', 'Urinary system and male reproductive health'),
(gen_random_uuid(), 'Ophthalmology', 'Eye health and vision care'),
(gen_random_uuid(), 'ENT (Ear, Nose, Throat)', 'Ear, nose, and throat conditions'),
(gen_random_uuid(), 'Pulmonology', 'Respiratory system and lung health'),
(gen_random_uuid(), 'Gastroenterology', 'Digestive system health'),
(gen_random_uuid(), 'Endocrinology', 'Hormone and metabolic disorders'),
(gen_random_uuid(), 'Infectious Diseases', 'Infectious disease diagnosis and treatment'),
(gen_random_uuid(), 'Geriatrics', 'Elderly care and aging-related health'),
(gen_random_uuid(), 'Sports Medicine', 'Sports-related injuries and performance'),
(gen_random_uuid(), 'Preventive Medicine', 'Disease prevention and wellness'),
(gen_random_uuid(), 'Alternative Medicine', 'Complementary and alternative therapies'),

-- Mental Health & Counseling
(gen_random_uuid(), 'Clinical Psychology', 'Clinical psychological assessment and therapy'),
(gen_random_uuid(), 'Counseling Psychology', 'Personal and emotional counseling'),
(gen_random_uuid(), 'Marriage & Family Therapy', 'Relationship and family counseling'),
(gen_random_uuid(), 'Child Psychology', 'Child development and behavioral therapy'),
(gen_random_uuid(), 'Addiction Counseling', 'Substance abuse and addiction treatment'),
(gen_random_uuid(), 'Trauma Therapy', 'Post-traumatic stress and trauma counseling'),
(gen_random_uuid(), 'Cognitive Behavioral Therapy', 'CBT techniques and approaches'),
(gen_random_uuid(), 'Dialectical Behavior Therapy', 'DBT for emotional regulation'),
(gen_random_uuid(), 'Art Therapy', 'Creative arts in therapeutic practice'),
(gen_random_uuid(), 'Music Therapy', 'Music-based therapeutic interventions'),
(gen_random_uuid(), 'Play Therapy', 'Play-based therapy for children'),
(gen_random_uuid(), 'Group Therapy', 'Group counseling and support sessions'),
(gen_random_uuid(), 'Crisis Intervention', 'Emergency mental health support'),
(gen_random_uuid(), 'Grief Counseling', 'Bereavement and loss support'),
(gen_random_uuid(), 'Anxiety Treatment', 'Anxiety disorders and management'),
(gen_random_uuid(), 'Depression Treatment', 'Depression and mood disorders'),
(gen_random_uuid(), 'Eating Disorders', 'Eating disorder treatment and recovery'),
(gen_random_uuid(), 'OCD Treatment', 'Obsessive-compulsive disorder therapy'),
(gen_random_uuid(), 'ADHD Support', 'Attention deficit hyperactivity disorder'),
(gen_random_uuid(), 'Autism Support', 'Autism spectrum disorder support'),
(gen_random_uuid(), 'LGBTQ+ Counseling', 'LGBTQ+ specific mental health support'),
(gen_random_uuid(), 'Veterans Counseling', 'Military and veteran mental health'),

-- Business & Professional Development
(gen_random_uuid(), 'Business Strategy', 'Strategic planning and business development'),
(gen_random_uuid(), 'Entrepreneurship', 'Starting and growing businesses'),
(gen_random_uuid(), 'Marketing Strategy', 'Marketing and brand development'),
(gen_random_uuid(), 'Digital Marketing', 'Online marketing and social media'),
(gen_random_uuid(), 'Sales Training', 'Sales techniques and customer acquisition'),
(gen_random_uuid(), 'Financial Planning', 'Personal and business financial planning'),
(gen_random_uuid(), 'Investment Advisory', 'Investment strategies and portfolio management'),
(gen_random_uuid(), 'Tax Planning', 'Tax strategies and compliance'),
(gen_random_uuid(), 'Human Resources', 'HR management and employee relations'),
(gen_random_uuid(), 'Leadership Development', 'Leadership skills and executive coaching'),
(gen_random_uuid(), 'Team Building', 'Team dynamics and collaboration'),
(gen_random_uuid(), 'Conflict Resolution', 'Workplace conflict management'),
(gen_random_uuid(), 'Negotiation Skills', 'Business negotiation and deal-making'),
(gen_random_uuid(), 'Time Management', 'Productivity and time optimization'),
(gen_random_uuid(), 'Project Management', 'Project planning and execution'),
(gen_random_uuid(), 'Change Management', 'Organizational change and transformation'),
(gen_random_uuid(), 'Customer Service', 'Customer experience and service excellence'),
(gen_random_uuid(), 'Operations Management', 'Business operations and efficiency'),
(gen_random_uuid(), 'Supply Chain Management', 'Supply chain optimization'),
(gen_random_uuid(), 'Quality Management', 'Quality assurance and process improvement'),
(gen_random_uuid(), 'Risk Management', 'Business risk assessment and mitigation'),
(gen_random_uuid(), 'Compliance', 'Regulatory compliance and governance'),

-- Legal & Professional Services
(gen_random_uuid(), 'Corporate Law', 'Business and corporate legal matters'),
(gen_random_uuid(), 'Family Law', 'Family and domestic relations law'),
(gen_random_uuid(), 'Criminal Law', 'Criminal defense and prosecution'),
(gen_random_uuid(), 'Real Estate Law', 'Property and real estate legal matters'),
(gen_random_uuid(), 'Intellectual Property', 'IP law and patent protection'),
(gen_random_uuid(), 'Employment Law', 'Workplace and employment legal issues'),
(gen_random_uuid(), 'Tax Law', 'Tax legal matters and compliance'),
(gen_random_uuid(), 'Immigration Law', 'Immigration and citizenship matters'),
(gen_random_uuid(), 'Estate Planning', 'Wills, trusts, and estate planning'),
(gen_random_uuid(), 'Contract Law', 'Contract drafting and negotiation'),
(gen_random_uuid(), 'Litigation', 'Civil litigation and dispute resolution'),
(gen_random_uuid(), 'Environmental Law', 'Environmental legal compliance'),
(gen_random_uuid(), 'Healthcare Law', 'Healthcare regulatory compliance'),
(gen_random_uuid(), 'Bankruptcy Law', 'Bankruptcy and debt relief'),
(gen_random_uuid(), 'Personal Injury', 'Personal injury and accident claims'),
(gen_random_uuid(), 'Mediation', 'Alternative dispute resolution'),
(gen_random_uuid(), 'Arbitration', 'Arbitration and conflict resolution'),

-- Education & Training
(gen_random_uuid(), 'Academic Tutoring', 'Subject-specific academic support'),
(gen_random_uuid(), 'Test Preparation', 'Standardized test preparation'),
(gen_random_uuid(), 'College Admissions', 'University application guidance'),
(gen_random_uuid(), 'Career Counseling', 'Career planning and development'),
(gen_random_uuid(), 'Language Learning', 'Foreign language instruction'),
(gen_random_uuid(), 'Special Education', 'Special needs education support'),
(gen_random_uuid(), 'Adult Education', 'Adult learning and skill development'),
(gen_random_uuid(), 'Online Learning', 'Digital education and e-learning'),
(gen_random_uuid(), 'Curriculum Development', 'Educational program design'),
(gen_random_uuid(), 'Educational Technology', 'EdTech integration and tools'),
(gen_random_uuid(), 'Student Success', 'Academic success and study skills'),
(gen_random_uuid(), 'Teacher Training', 'Professional development for educators'),
(gen_random_uuid(), 'Early Childhood Education', 'Preschool and early learning'),
(gen_random_uuid(), 'STEM Education', 'Science, technology, engineering, math'),
(gen_random_uuid(), 'Literacy Development', 'Reading and writing skills'),
(gen_random_uuid(), 'Mathematics Education', 'Math teaching and learning'),
(gen_random_uuid(), 'Science Education', 'Science teaching and learning'),
(gen_random_uuid(), 'Arts Education', 'Creative arts and music education'),
(gen_random_uuid(), 'Physical Education', 'Sports and fitness education'),

-- Creative & Media
(gen_random_uuid(), 'Creative Writing', 'Fiction, non-fiction, and creative writing'),
(gen_random_uuid(), 'Content Creation', 'Digital content and media creation'),
(gen_random_uuid(), 'Video Production', 'Video creation and editing'),
(gen_random_uuid(), 'Photography', 'Photography techniques and skills'),
(gen_random_uuid(), 'Graphic Design', 'Visual design and branding'),
(gen_random_uuid(), 'Web Design', 'Website design and development'),
(gen_random_uuid(), 'Animation', '2D and 3D animation techniques'),
(gen_random_uuid(), 'Game Design', 'Video game design and development'),
(gen_random_uuid(), 'Music Production', 'Music recording and production'),
(gen_random_uuid(), 'Podcasting', 'Podcast creation and production'),
(gen_random_uuid(), 'Social Media Management', 'Social media strategy and content'),
(gen_random_uuid(), 'SEO Optimization', 'Search engine optimization'),
(gen_random_uuid(), 'Copywriting', 'Marketing copy and content writing'),
(gen_random_uuid(), 'Technical Writing', 'Technical documentation and manuals'),
(gen_random_uuid(), 'Journalism', 'News writing and reporting'),
(gen_random_uuid(), 'Public Relations', 'PR strategy and media relations'),
(gen_random_uuid(), 'Event Planning', 'Event coordination and management'),
(gen_random_uuid(), 'Fashion Design', 'Fashion and apparel design'),
(gen_random_uuid(), 'Interior Design', 'Interior design and decoration'),
(gen_random_uuid(), 'Architecture', 'Architectural design and planning'),

-- Fitness & Wellness
(gen_random_uuid(), 'Personal Training', 'Personal fitness and strength training'),
(gen_random_uuid(), 'Nutrition Coaching', 'Nutrition and dietary guidance'),
(gen_random_uuid(), 'Yoga Instruction', 'Yoga practice and mindfulness'),
(gen_random_uuid(), 'Pilates Training', 'Pilates and core strengthening'),
(gen_random_uuid(), 'Meditation', 'Meditation and mindfulness practices'),
(gen_random_uuid(), 'Weight Loss Coaching', 'Weight management and fitness'),
(gen_random_uuid(), 'Sports Coaching', 'Athletic training and performance'),
(gen_random_uuid(), 'Rehabilitation', 'Physical therapy and recovery'),
(gen_random_uuid(), 'Wellness Coaching', 'Holistic health and wellness'),
(gen_random_uuid(), 'Stress Management', 'Stress reduction and relaxation'),
(gen_random_uuid(), 'Sleep Coaching', 'Sleep improvement and optimization'),
(gen_random_uuid(), 'Functional Training', 'Functional movement and fitness'),
(gen_random_uuid(), 'CrossFit Training', 'CrossFit and high-intensity training'),
(gen_random_uuid(), 'Running Coaching', 'Running technique and training'),
(gen_random_uuid(), 'Swimming Instruction', 'Swimming technique and training'),
(gen_random_uuid(), 'Cycling Coaching', 'Cycling technique and training'),
(gen_random_uuid(), 'Dance Instruction', 'Dance and movement training'),
(gen_random_uuid(), 'Martial Arts', 'Martial arts training and self-defense'),
(gen_random_uuid(), 'Mind-Body Connection', 'Mind-body wellness practices'),

-- Technology (Expanded)
(gen_random_uuid(), 'Healthcare IT', 'Healthcare technology and systems'),
(gen_random_uuid(), 'FinTech', 'Financial technology and digital banking'),
(gen_random_uuid(), 'EdTech', 'Educational technology solutions'),
(gen_random_uuid(), 'Legal Tech', 'Legal technology and automation'),
(gen_random_uuid(), 'Green Tech', 'Environmental and sustainable technology'),
(gen_random_uuid(), 'Biotechnology', 'Biotech and life sciences technology'),
(gen_random_uuid(), 'Robotics', 'Robotics and automation systems'),
(gen_random_uuid(), 'Quantum Computing', 'Quantum computing and algorithms'),
(gen_random_uuid(), 'Data Privacy', 'Data protection and privacy compliance'),
(gen_random_uuid(), 'Cloud Computing', 'Cloud infrastructure and services'),
(gen_random_uuid(), 'DevOps', 'Development and operations practices'),
(gen_random_uuid(), 'Software Architecture', 'Software system design'),
(gen_random_uuid(), 'API Development', 'Application programming interfaces'),
(gen_random_uuid(), 'Database Design', 'Database architecture and optimization'),
(gen_random_uuid(), 'Mobile App Development', 'Mobile application development'),
(gen_random_uuid(), 'Web Development', 'Web application development'),
(gen_random_uuid(), 'Game Development', 'Video game programming'),
(gen_random_uuid(), 'AI/ML Development', 'Artificial intelligence and machine learning'),
(gen_random_uuid(), 'Blockchain Development', 'Blockchain and cryptocurrency'),
(gen_random_uuid(), 'IoT Development', 'Internet of Things development'),
(gen_random_uuid(), 'AR/VR Development', 'Augmented and virtual reality'),
(gen_random_uuid(), 'Embedded Systems', 'Embedded software and hardware'),
(gen_random_uuid(), 'Network Engineering', 'Computer networking and infrastructure'),

-- Specialized Services
(gen_random_uuid(), 'Life Coaching', 'Personal development and life goals'),
(gen_random_uuid(), 'Executive Coaching', 'Executive leadership development'),
(gen_random_uuid(), 'Career Transition', 'Career change and transition support'),
(gen_random_uuid(), 'Resume Writing', 'Resume and CV optimization'),
(gen_random_uuid(), 'Interview Coaching', 'Job interview preparation'),
(gen_random_uuid(), 'Networking', 'Professional networking strategies'),
(gen_random_uuid(), 'Personal Branding', 'Personal brand development'),
(gen_random_uuid(), 'Work-Life Balance', 'Work-life integration strategies'),
(gen_random_uuid(), 'Remote Work', 'Remote work and virtual collaboration'),
(gen_random_uuid(), 'Diversity & Inclusion', 'DEI training and consulting'),
(gen_random_uuid(), 'Cultural Competency', 'Cross-cultural communication'),
(gen_random_uuid(), 'Accessibility', 'Accessibility and inclusive design'),
(gen_random_uuid(), 'Sustainability', 'Environmental sustainability practices'),
(gen_random_uuid(), 'Social Impact', 'Social entrepreneurship and impact'),
(gen_random_uuid(), 'Nonprofit Management', 'Nonprofit organization leadership'),
(gen_random_uuid(), 'Grant Writing', 'Grant proposal and fundraising'),
(gen_random_uuid(), 'Volunteer Management', 'Volunteer coordination and engagement'),
(gen_random_uuid(), 'Community Development', 'Community building and engagement'),
(gen_random_uuid(), 'International Development', 'Global development projects'),
(gen_random_uuid(), 'Humanitarian Aid', 'Humanitarian assistance and relief'),
(gen_random_uuid(), 'Disaster Response', 'Emergency response and recovery'),
(gen_random_uuid(), 'Public Policy', 'Policy analysis and advocacy'),
(gen_random_uuid(), 'Government Relations', 'Government affairs and lobbying'),
(gen_random_uuid(), 'Political Consulting', 'Political strategy and campaigns'),
(gen_random_uuid(), 'Media Relations', 'Media strategy and communications'),
(gen_random_uuid(), 'Crisis Communications', 'Crisis management and communication'),
(gen_random_uuid(), 'Reputation Management', 'Online reputation and brand protection')
ON CONFLICT (name) DO NOTHING; 