// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://antxwhzyxltmqgluhhxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudHh3aHp5eGx0bXFnbHVoaHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODUwMDQsImV4cCI6MjA2NTc2MTAwNH0.hgvXgt6_peieUHRoIb2HSIRAPFYNX8V1J41iIlei7do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);